### ISSUE TITLE
Getting "MixpanelReactNative is null" on fresh install

### ISSUE THREAD

**Issue by crrobinson14** [mixpanel/mixpanel-react-native#46] opened 2021-05-06 15:06 UTC
I just tried adding this module to a project and am getting this error when calling Mixpanel.init() with my key. The error says "Please follow the guide on Github" but the only thing I see is in the README calling for adding the module and running `pod install`, the usual procedure. I have done that, and can confirm my Podfile.lock contains the appropriate modules (`pod install` also reported installing them):

```
...
  - Mixpanel-swift (2.9.3):
    - Mixpanel-swift/Complete (= 2.9.3)
  - Mixpanel-swift/Complete (2.9.3)
  - MixpanelReactNative (1.2.0):
    - Mixpanel-swift (= 2.9.3)
    - React
...
```

Any thoughts?

**Comment by zihejia** [comment] 2021-05-06 16:30
hi @crrobinson14 , could you share your code snippet for how you init Mixpanel?

**Comment by crrobinson14** [comment] 2021-05-06 17:22
@zihejia Sure, but there's not much to it:

```
import {Mixpanel} from 'mixpanel-react-native';

Mixpanel.init('MYKEY');
...

**Comment by zihejia** [comment] 2021-05-06 17:39
hi @crrobinson14 , where do you put `Mixpanel.init`? Or better if you could make a minimum js file that could help me to reproduce the issue would be great!

**Comment by jasonkv** [comment] 2021-05-06 22:37
We are getting a similar error (migrating from react-native-mixpanel) to this official library.

The code is in App.js
``` 
async componentDidMount() {
 await Mixpanel.init(MIXPANEL_TOKEN);
}

```

```
[TypeError: undefined is not an object (evaluating '_mixpanelReactNative.default.init')]
```

**Comment by crrobinson14** [comment] 2021-05-07 03:18
OK so I was able to get this working. What I did was the old trick you often have to do with Firebase, in the `ios` folder I ran `rm Podfile.lock && pod install --repo-update`. It seems to have resolved it for me so far...

**Comment by jasonkv** [comment] 2021-05-07 17:52
Unfortunately that seems to have not worked, still getting the same error. 

Here is the Podfile.lock & mixpanel lines:

```

  - Mixpanel-swift (2.9.3):
    - Mixpanel-swift/Complete (= 2.9.3)
  - Mixpanel-swift/Complete (2.9.3)
  - MixpanelReactNative (1.2.0):
    - Mixpanel-swift (= 2.9.3)
    - Reac
```

**Comment by zihejia** [comment] 2021-05-07 19:16
hi @jasonkv , I could not replicate the issue. Any chance you attach a complete sample(zip) here?

**Comment by jasonkv** [comment] 2021-05-07 21:24
Thanks for your help.  We'll try to see if we can produce a sample(zip) with the problem if we do continue to try to migrate.

For now we are sticking with the old library from davodesign84  we are already using since it does seem that it now uses mixpanel 3.6.2  SDK which doesn't use IDFA and that was our main concern.

**Comment by crrobinson14** [comment] 2021-05-14 19:51
Correction to my comment above. Actually, I am still reproducing this, but only in the simulator. If I run on device it seems OK. Does Mixpanel disable itself on the simulator somehow?

**Comment by karanasthana** [comment] 2021-06-03 07:29
Hi,

I've been facing the same issue `MixpanelPeactNative is null`.

I have just recently installed the mixpanel-react-native library. 

Config -
```
  - Mixpanel-swift (2.9.3):
    - Mixpanel-swift/Complete (= 2.9.3)
  - Mixpanel-swift/Complete (2.9.3)
  - MixpanelReactNative (1.2.3):
    - Mixpanel-swift (= 2.9.3)
    - React
```

This is how I am importing/using it -- 
```
import { Mixpanel } from 'mixpanel-react-native';

export default class App extends React.Component {
    constructor(props) {
        super(props);
        this.configMixpanel();
    }
    configMixpanel = async () => {
        this.mixpanel = await Mixpanel.init('fc82dac32598834f44e8e607ac1708d8');
    };
```
    
PS - I have tried by removing pods, podfile.lock and even deintegrate pods, but none seemed to work for me. 
PPS - I too am using it on a simulator. Does that mean, I can no longer use simulator if I am to use mixpanel-react-native ?

**Comment by shvekiasaf** [comment] 2021-07-04 13:03
facing the same issue

**Comment by dipalinjawale** [comment] 2021-07-20 09:00
facing the same issue.
The demo project given in this repo is working fine in emulator but the same implementation is not working in my project.

**Comment by zihejia** [comment] 2021-07-21 21:44
This issue might be related to the improper initialization of Mixpanel. #70 
We will improve our examples and provide more tips for this. Can anyone share a minimum sample app or a js file causing the issue? It will be super helpful for us to understand more corner cases.

**Comment by zihejia** [comment] 2021-07-29 22:58
The Mixpanel class method `init()` is potentially causing issues and we are now deprecating it. 
Please try our latest version 1.3.1 and use the instance method `init()` instead. 
```
import { Mixpanel } from 'mixpanel-react-native';

const mixpanel = new Mixpanel("Your Project Token");
mixpanel.init();
```

More examples: https://github.com/mixpanel/mixpanel-react-native/tree/master/Samples. 

This folder contains 3 sample applications demonstrating how you can use Mixpanel in your React Native app.

SimpleMixpanel: Integrate Mixpanel with a minimalist approach
MixpanelDemo: A full Mixpanel API demo app
ContextAPIMixpanel: Integrate Mixpanel with Context API

I'm closing this one now. Please feel free to reopen if you have any issues.

**Closed by zihejia** 2021-07-29 22:58 UTC

**Comment by yarikpwnzer** [comment] 2021-08-06 18:58
@zihejia getting error on jest tests:
mixpanel-react-native: MixpanelReactNative is null.
Lib version 1.3.1

"transformIgnorePatterns": [
    "/node_modules/(?!react-native-config|@react-native|react-native|mixpanel-react-native)"
]

On device/simulators it's running well.

**Comment by zihejia** [comment] 2021-08-09 17:28
hi @yarikpwnzer , which jest tests are you referring to?

**Comment by MFazal1996** [comment] 2021-09-15 12:21
Re-running the app worked for me.

**Comment by Jy411** [comment] 2021-09-17 08:42
> @zihejia getting error on jest tests:
> mixpanel-react-native: MixpanelReactNative is null.
> Lib version 1.3.1
> 
> "transformIgnorePatterns": [
> "/node_modules/(?!react-native-config|@react-native|react-native|mixpanel-react-native)"
> ]
> 
> On device/simulators it's running well.

Any solutions for this?

**Comment by hashkazi00** [comment] 2022-02-10 13:49
any resolutions to this?

**Comment by qasimgit** [comment] 2022-05-02 13:15
@zihejia 
facing the same issue after installing the latest version 1.3.10 and pods

**useEffect(() => {
    const mixPanel = new Mixpanel(KEY);
    mixPanel.init();
  }, []);**

**Comment by brito-bc** [comment] 2022-09-13 22:00
> @zihejia getting error on jest tests: mixpanel-react-native: MixpanelReactNative is null. Lib version 1.3.1
> 
> "transformIgnorePatterns": [ "/node_modules/(?!react-native-config|@react-native|react-native|mixpanel-react-native)" ]
> 
> On device/simulators it's running well.

For anyone having this issue, it gets fixed by mocking `mixpanel-react-native` as suggested on this [comment](https://github.com/mixpanel/mixpanel-react-native/issues/88#issuecomment-930356702):

```
jest.mock("mixpanel-react-native", () => ({
  __esModule: true,
  default: () => jest.fn(),
  Mixpanel: jest.fn(() => ({
    init: jest.fn(),
  })),
}));
```

**Comment by lucarducci** [comment] 2022-11-18 15:18
Facing the same error on macbook with simulator and on Expo on IOS device.

Event the sample projects have different errors on the installation

**Comment by lucarducci** [comment] 2022-11-18 15:20
Can we reopen the issue? @zihejia

**Comment by RomneyDa** [comment] 2022-11-30 12:41
I second that, can we reopen?
Seeing same issue on react native expo with web, simulator, and physical device. Haven't found any solutions online yet.

Error:
mixpanel-react-native: MixpanelReactNative is null.

I'm not even ever calling mixpanel methods or mixpanel.init(). This error occurs in imports, not because of a failed attempt to track an event. If I do init with or without tracking, same error.

**Comment by SaileshKumar** [comment] 2022-12-05 20:37
Ditto, happening for me, am also using expo

**Comment by Slicefresh22** [comment] 2023-01-11 23:33
Facing the same issue as well.

**Comment by createlyn** [comment] 2023-02-05 20:33
I'm having this issue as well

**Comment by lmn451** [comment] 2023-03-17 19:36
Hey, probably you need to open you project with xcode and click play button. It will do some magick and the app should work. 


At least it worked for me

**Comment by portermichael** [comment] 2023-04-17 00:23
This issue is higher in the SEO world, so if you're running into MixpanelReactNative is null, check out the solution in issue 82: https://github.com/mixpanel/mixpanel-react-native/issues/82
