### ISSUE TITLE
Mixpanel.library is always displayed react-native

### ISSUE THREAD

**Issue by gundomlegend** [mixpanel/mixpanel-react-native#92] opened 2021-09-08 02:41 UTC
Before I use this library, `android / ios` will be displayed in `Mixpanel.library` property. But when I upgrade to this library, only `react-native` will be displayed in `Mixpanel.library` property. Could you support this feature like [this library](https://github.com/davodesign84/react-native-mixpanel) ?

**Comment by zihejia** [comment] 2021-09-21 21:49
hi @gundomlegend , why do you need it to be displayed as `android / ios` if you are indeed using a react-native library? If you need the platform information, you can use the `OS` property.

**Comment by zihejia** [comment] 2021-09-23 21:18
Hi @gundomlegend , since this is not a bug, I'm closing this one now. But please feel free to raise any more questions or reopen it.

**Closed by zihejia** 2021-09-23 21:18 UTC
