### ISSUE TITLE
It only track on iOS in Android nothing at all

### ISSUE THREAD

**Issue by pixsolution** [mixpanel/mixpanel-react-native#56] opened 2021-05-14 15:01 UTC
Hello,

I installed your library in two projects following your doc and does not work in android in ios work well. And I just tried a third project a new React Native project from scratch, with nothing at all, we just installed your library and put a basic track to try to see and nothing that works in android, I leave below what exactly I did with this last case of RN project from scratch:

First try like this as you have on your demo:

```
import {Mixpanel} from 'mixpanel-react-native';
import {token as MixpanelToken} from './app.json';

export default class MixpanelManager {
 static sharedInstance = MixpanelManager.sharedInstance || new MixpanelManager(); constructor() {
 this.configMixpanel();
 } configMixpanel = async () => {
 this.mixpanel = await Mixpanel.init(MixpanelToken);
 };
} 
```

The following was done in the Component:

```
constructor(props) {
 super(props);
 this.mixpanel = MixpanelManager.sharedInstance.mixpanel;
 }
```

then the method is called

```
track = () => {
 this.mixpanel.track('Track Event!');
 };
```
It does not show any Error but does not mark any Track on the Live View

I also tried as you said in your doc

```
export default class App extends Component {
 constructor(props) {
 super(props);
 this.configMixpanel();
 } configMixpanel = async () => {
 this.mixpanel = await Mixpanel.init('my_token');
 };
```

This causes a Warning
![Capture 1](https://user-images.githubusercontent.com/47191848/118288658-ea2fce00-b4d4-11eb-9a23-f96f08916c10.jpeg)

then when mixpanel.track ('someEvent') is called; causes the following Error
![Capture 2](https://user-images.githubusercontent.com/47191848/118288708-f3209f80-b4d4-11eb-9e96-57ca532bad42.jpeg)

then what happen in android? because in ios it works...

Regards

**Comment by pixsolution** [comment] 2021-05-29 10:04
Hi @zihejia thanks for your reply and sorry for the delay I did not see the notification. In this link [https://wetransfer.com/downloads/bbecb3354846935aa94fa9cbfb4d8fac20210528205313/d9647c3c51e60b8cfe23e8b3d242013b20210528205338/258f5d](url) or here [https://pixsolution-my.sharepoint.com/:u:/g/personal/jacm_pixsolution_onmicrosoft_com/EfqzrUo-8vtEj-24jW1IzOsBnoEt095IkxoX8sZrTJ-2HQ?e=Pte7sv](url)
you can see the app without src code 
but above you can see how I applied like you said on your doc...and as I told in iOS work well

I'll be waiting for your reply
Thanks
Regards

**Comment by pixsolution** [comment] 2021-06-09 12:42
Hello @zihejia could you see that? any news?

**Comment by zihejia** [comment] 2021-07-21 21:17
hi @pixsolution , I'm very very sorry for the late response. I can reproduce the issue by using the sample app you provided. The issue is that you have called `mixpanel.track` too early before it is being initialized. We will revise the example and provide more tips in our docs for using Mixpanel. You can use this #70 to track the progress. I've also noticed you have been in conversation with our support team, we will give you an update from there as well. I'm closing this issue for now.

**Closed by zihejia** 2021-07-21 21:17 UTC
