### ISSUE TITLE
Not able to build IOS app after installing the library

### ISSUE THREAD

**Issue by dpk89** [mixpanel/mixpanel-react-native#28] opened 2021-02-10 17:14 UTC
<h2>How i integrated</h2>
`npm install mixpanel-react-native`

then in ios directory `pod install`

After that  when i run the app 
i receive these errors on xcode 

<img width="412" alt="Screenshot at Feb 10 23-24-42" src="https://user-images.githubusercontent.com/39826327/107550571-34b05e80-6bf7-11eb-84b6-0162f9ebe627.png">
`React-native version 0.61.5`

**Comment by zihejia** [comment] 2021-02-27 19:32
hi @dpk89 , sorry for the late response. However, I'm not able to reproduce. Could you paste more logs to indicate which pod and files caused this error. Also, could you try to delete your Pods folder and redo the `pod install` and then do a [clean build](https://developerinsider.co/clean-xcode-cache-quick-fix/#:~:text=To%20clean%20the%20build%20folder,Key%20%E2%86%92%20Clean%20build%20Folder%20.)?

**Comment by zihejia** [comment] 2021-03-03 20:13
I'm closing this issue now, please feel free to reopen it if the problem still exists. Thanks!

**Closed by zihejia** 2021-03-03 20:13 UTC
